name: CI
on:
  push:
    branches:
      - "main"
jobs:
  test:
    name: Execute Unit Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn test
  release:
    name: Release
    needs: test
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn build
      - run: yarn global add semantic-release-cli
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
